name: Send Mail on Push

on:
  push:
    branches: [main]  # Triggers the workflow when pushing to main
   
jobs:
  send_email:
    runs-on: ubuntu-latest
    env: 
        APP_NAME: Marketplace Email Integration

    steps:
      - name: Send email using Gmail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USER }}
          password: ${{ secrets.GMAIL_PASS }}
          subject: GitHub Actions Email Test For Assignment
          to: ${{ secrets.GMAIL_USER }}
          from: ${{ secrets.GMAIL_USER }}
          content_type: text/plain
          body: |
                     Hello Team,
                     The CI/CD workflow for the ${{env.APP_NAME}} application has successfully executed.
                     Key Learining:
                        - Implemented a full GitHub Actions workflow for continuous integration and deployment.
                        - Utilized various types of variables across workflows, jobs, and steps to manage configurations.
                        - Integrated actions from the GitHub Marketplace to streamline setup and deployment processes.
                        - Applied secure secret handling using GitHub Secrets to manage sensitive data.

                        
                        Repository URL:
                        https://github.com/roxter207/ica-activity

                        Regards,  
                        Group Members
